#!/bin/sh

path="/mnt/tftp"

global.bootm.image="${path}/uImage-mini2440"

oftree="${path}/${global.user}-oftree-${global.hostname}"
if [ -f "${oftree}" ]; then
	global.bootm.oftree="$oftree"
fi

nfsroot="/home/sam/Documenten/buildroot/output/images/myrootfs"
bootargs-ip

initramfs="${path}/${global.user}-initramfs-${global.hostname}"
if [ -f "${initramfs}" ]; then
	global.bootm.initrd="$initramfs"
else
	global.linux.bootargs.dyn.root="root=/dev/nfs nfsroot=$nfsroot,v3,tcp"
fi
